"""empty message

Revision ID: 44a8b6e49c35
Revises: 
Create Date: 2021-09-08 04:14:07.087244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a8b6e49c35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setId', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('series', sa.String(length=120), nullable=True),
    sa.Column('printedTotal', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('ptcgoCode', sa.String(length=120), nullable=True),
    sa.Column('releaseDate', sa.String(length=120), nullable=True),
    sa.Column('updatedAt', sa.String(length=120), nullable=True),
    sa.Column('symbolUrl', sa.String(length=120), nullable=True),
    sa.Column('logoUrl', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setId')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('card_set')
    # ### end Alembic commands ###
